server:
  port: 8081
grpc:
  server:
    port: 9092

spring:
  application:
    name: scrapper
    scheduler-interval: PT60S
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/migrations/master.xml
    url: ${DATASOURCE_URL}
    user: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}

  config:
      import: file:.env[.properties]

app:
  access-type: SQL
  stackoverflow:
    key: ${STACKOVERFLOW_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    access-token: ${STACKOVERFLOW_ACCESS_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    base-url: "https://api.stackexchange.com/2.3"
  github:
    token: ${GITHUB_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    base-url: "https://api.github.com"
  bot:
    base-url: "http://localhost:8080"
    grpc:
      host: "localhost"
      port: 9091
debug: true
