server:
  port: 8081
grpc:
  server:
    port: 9093

spring:
  devtools:
    restart:
      enabled: false

  cache:
    type: redis

  data:
    redis:
      password: ${VALKEY_PASSWORD}

      cluster:
        nodes:
          - localhost:7000
          - localhost:7001
          - localhost:7002
          - localhost:7003
          - localhost:7004
          - localhost:7005

  datasource:
    url: ${SCRAPPER_DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/migrations/master.xml
    url: ${SCRAPPER_DATASOURCE_URL}
    user: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}

  kafka:
    bootstrap-servers: localhost:19092

    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

      properties:
        schema.registry.url: http://localhost:8083

        acks: all
        enable.idempotence: true

  config:
      import: optional:file:.env[.properties]

app:
  scheduler:
    delay: PT60S
    batch-size: 50
    threads: 4
    termination-await-millis: 90000

  outbox:
    batch-size: 50
    max-retry: 5
    termination-await-millis: 90000
    threads: 4

  cache:
    ttl: 600

  kafka:
    topic-link-update: linkUpdateEvent
    partitions: 3
    replicas: 2
    dlt-suffix: -dlt

  message-sending-type: KAFKA
  access-type: SQL
  stackoverflow:
    key: ${STACKOVERFLOW_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    access-token: ${STACKOVERFLOW_ACCESS_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    base-url: "https://api.stackexchange.com/2.3"
  github:
    token: ${GITHUB_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    base-url: "https://api.github.com"
  bot:
    base-url: "http://localhost:8080"
    grpc:
      host: "localhost"
      port: 9091
debug: false
