server:
  port: 8081
grpc:
  server:
    port: 9093

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/migrations/master.xml
    url: ${DATASOURCE_URL}
    user: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}

  kafka:
    bootstrap-servers: localhost:19092
    producer:
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  config:
      import: optional:file:.env[.properties]

app:
  scheduler:
    delay: PT60S
    batch-size: 50
    threads: 4
    termination-await-millis: 90000

  kafka:
    topic-link-update: linkUpdateEvent
    partitions: 1
    replicas: 1

  message-sending-type: KAFKA
  access-type: SQL
  stackoverflow:
    key: ${STACKOVERFLOW_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    access-token: ${STACKOVERFLOW_ACCESS_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    base-url: "https://api.stackexchange.com/2.3"
  github:
    token: ${GITHUB_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    base-url: "https://api.github.com"
  bot:
    base-url: "http://localhost:8080"
    grpc:
      host: "localhost"
      port: 9091
