server:
  port: 8080
grpc:
  server:
    port: 9091

spring:
  application:
    name: bot
  config:
    import: optional:file:.env[.properties]
  messages:
    encoding: UTF-8

  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.LongDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.type.mapping: "linkUpdateEvent:backend.academy.linktracker.bot.dto.LinkUpdateMessage"
    producer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false
  kafka:
    retry-interval: 1000
    retry-max-attempts: 3

  message:
    basename: classpath:messages
  scrapper:
    base-url: "http://localhost:8081"
    grpc:
      host: "localhost"
      port: 9093


logging:
  level:
    root: info
  structured:
    format:
#      console: ecs
      file: ecs
  file:
    name: log/log.json
