server:
  port: 8080
grpc:
  server:
    port: 9091

spring:
  application:
    name: bot

  datasource:
    url: ${BOT_DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/migrations/master.yaml
    url: ${BOT_DATASOURCE_URL}
    user: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}

  devtools:
    restart:
      enabled: false
  config:
    import: optional:file:.env[.properties]
  messages:
    encoding: UTF-8

  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: linkUpdateGroup

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.LongDeserializer
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        schema.registry.url: http://localhost:8083
        specific.avro.reader: true

    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

      properties:
        schema.registry.url: http://localhost:8083


app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false
  kafka:
    retry-interval: 1000
    retry-max-attempts: 3

  message:
    basename: classpath:messages
  scrapper:
    base-url: "http://localhost:8081"
    grpc:
      host: "localhost"
      port: 9093


logging:

  level:
    org.springframework.kafka: INFO
    org.apache.kafka: INFO
    root: info
  structured:
    format:
#      console: ecs
      file: ecs
  file:
    name: log/log.json

